testing/integration-tests/src/test/java/org/glowroot/tests/javaagent/DataSourceShutdownTest.java

Just as the comment says, when an OSX JVM is launched in debug mode, it chirps, but the test should _otherwise_ not have any output

Update integration tests for OSX jvm chatter

---

ui/src/main/java/org/glowroot/ui/InstrumentationConfigJsonService.java

The commit here fixes an issue in the web UI feature of "Import" instrumentation config JSON, where it currently ignores the `methodAnnotation` and `classAnnotation` attributes that may have been specified in the config JSON.

Fix instrumentation import JSON from UI to pass methoAnnotation and classAnnotation

---

central/pom.xml

While building glowroot, I sometimes randomly run into issue where the glowroot central jar that gets created, via the central/pom.xml maven-jar-plugin configurations, cannot be used to run it as a standalone application through:
```
unzip target/glowroot*-dist.zip -d foo
cd foo/glowroot-central
java -jar glowroot-central.jar
```
That commands runs into an error stating that the jar's manifest is missing the `Main-Class` attribute. Of course, that is a sign that the jar itself is missing a bunch of other stuff.
It's not always the case though, sometimes it just works. So I read up the maven-jar-plugin documentation here [1] which has some relevant information about the `forceCreation` attribute for this plugin's `jar` goal. It looks like we are running into this issue with the …

Fix a bug which would create an incorrect central jar

---

agent/core/src/main/java/org/glowroot/agent/config/InstrumentationConfig.java
agent/core/src/main/java/org/glowroot/agent/weaving/AdviceBuilder.java
agent/core/src/main/java/org/glowroot/agent/weaving/AdviceGenerator.java
ui/app/scripts/controllers/config/instrumentation-list.js
ui/app/scripts/controllers/config/instrumentation.js
ui/app/scripts/services/instrumentation-export.js
ui/src/main/java/org/glowroot/ui/InstrumentationConfigJsonService.java
wire-api/src/main/proto/AgentConfig.proto

The commit here adds support to the instrumentation config JSON to use the `superTypeRestriction` feature that was introduced in this commit https://github.com/glowroot/glowroot/commit/e3301aa15d08fc3497da2fd5ac8ac76b2ddcf1be

Add support for superTypeRestriction in instrumentation config JSON

---

agent/plugins/java-http-server-plugin/src/main/java/org/glowroot/agent/plugin/javahttpserver/DetailCapture.java
agent/plugins/java-http-server-plugin/src/test/java/org/glowroot/agent/plugin/javahttpserver/RequestHeaderIT.java
agent/plugins/java-http-server-plugin/src/test/java/org/glowroot/agent/plugin/javahttpserver/ResponseHeaderIT.java

- Added `ImmutableList<Pattern> maskPatterns` argument to `DetailCapture.captureHeaders(...)` method signature.
- Added tests.

Java HTTP Server plugin: fixed bug that caused masking of response headers.

---

pom.xml

Class file where located in `classes.jar` only in the Apple supplied JDKs up to JDK 6.

Fix build on macOS

---

central/Dockerfile

glowroot-central: Docker image: create group/user glowroot and change user to glowroot:glowroot to avoid running image as root (otherwise, image cannot be used e.g. on OpenShift).

glowroot-central: Change user in docker image to avoid image run as root

---

README.md

I've saw a small mistake on `README.md` file when a link to agent benchmarks doesn't worked.
Congrats for your impressive work!
Regards,
Bruno

Fix link to benchmarks project on README

---

agent/plugins/spring-plugin/src/main/resources/META-INF/glowroot.plugin.json

Hi,
I would like to add `@RabbitListener` annotation support in the spring-plugin.
Here is the documentation related to this spring-amqp feature:
https://docs.spring.io/spring-amqp/reference/html/#async-annotation-driven
Here is the sample spring-rabbitmq project I used to test the spring-plugin configuration I propose to add:
https://github.com/Nowheresly/spring-rabbitmq-glowroot

Add RabbitListener support for spring-plugin

---

central/Dockerfile

Fixes #616 
Embed the commands to give execution permissions to `docker-entrypoint.sh` and `glowroot-central.sh`.

Add execution permissions to entrypoint and cmd scripts

---

central/src/main/conf/glowroot-central.properties
central/src/main/java/org/glowroot/central/CentralModule.java

This PR the Central Collector to be flexible in when connecting to a cassandra cluster. More specifically, the application can to connect to Azure Cosmos DB Cassandra API using port = 10350 and ssl = true.

Add support for Cassandra ssl and port options in central collector

---

central/pom.xml
pom.xml

We're using this for our own Glowroot cluster and I figured I'd contribute the work in case someone else could make use of it (and also so that we wouldn't have to keep building Central ourselves).
This adds the jgroups-kubernetes discovery protocol such that the Kubernetes cluster API is the authoritative source of jgroups cluster members (ideal when running a Glowroot Central cluster in Kubernetes). 
A Maven Enforcer exclusion has been added for org.jgroups:jgroups as jgroups-kubernetes depends on jgroups 4.1.x however it does work with 4.0.x. This can be removed once infinispan 10.x is released as that version is compatible with jgroups 4.1.x.

Add Jgroups Kubernetes discovery protocol

---

ui/app/hbs/trace.hbs
ui/app/scripts/handlebars-rendering.js

3690,123.4 milliseconds -> 1 hour 1.5 minutes
122,123.7 milliseconds -> 2 minutes 2.1 seconds
34,000.8 milliseconds -> 34,000.8 milliseconds

Format trace duration milliseconds in a more readable way

---

pom.xml

Hi @trask, this is a very simple PR to upgrade assertj.
You could find here informations abbout assertj releases:
https://assertj.github.io/doc/#assertj-core-java-versions
Since we are now using java8, it is safe to switch to the latest version of assertj.

Upd assertj 3.21.0

---

agent/plugins/logger-plugin/pom.xml
pom.xml

These 2 libs seem safe to be upgraded to the latest stable version.
https://github.com/qos-ch/slf4j/compare/v_1.7.30...v_1.7.32
https://github.com/qos-ch/logback/compare/v_1.2.3...v_1.2.6

Upd logback + slf4j upgrade

---

agent/core/src/main/java/org/glowroot/agent/init/FileSystem.java
agent/core/src/main/java/org/glowroot/agent/live/LiveJvmServiceImpl.java

[https://docs.oracle.com/javase/8/docs/api/java/io/File.html#getUsableSpace--](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#getUsableSpace--)
> Returns the number of bytes available to this virtual machine on the partition named by this abstract pathname. When possible, this method checks for write permissions and other operating system restrictions and will therefore usually provide a more accurate estimate of how much new data can actually be written than getFreeSpace().

Fix inaccurate free space checking

---

ui/app/scripts/clipboard.js

Hi @trask ,
This solves a bug related to `Copy to clipboard` button. The tooltip text wasn't changing to `Copied!` after clicking on it

Fix `Copied!` tooltip

---

central/Dockerfile

Closes #773 by employing unix group root for glowroot user and filesystem permissions.

Issue 773 open shift

---

central/Dockerfile

While doing PR #907 , I realized that a small optimization could be done to the dockerfile so that the size of the image could be reduced.
By running the following command:
`docker history glowroot/glowroot-central:0.14.0-beta.2`
we can see the following output:
```
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
e8d2b2bfd824   4 months ago   CMD ["glowroot-central.sh"]                     0B        buildkit.dockerfile.v0
<missing>      4 months ago   ENTRYPOINT ["docker-entrypoint.sh"]             0B        buildkit.dockerfile.v0
<missing>      4 months ago   ENV GLOWROOT_OPTS=-XX:+UnlockExperimentalVMO…   0B        buildkit.dockerfile.v0
<missing>      4 months ago   USER glowroot:glowroot                          0B …
```

Optimize docker image size

---

central/Dockerfile

Hi @trask 
it seems there was a small issue in PR #774 . The group glowroot does not exist anymore, thus the user can't be `glowroot:.glowroot` anymore.
This PR fixes this issue.
Example:
`docker run --rm -it glowroot/glowroot-central:0.14.beta3 bash`
crash with error:
`docker: Error response from daemon: unable to find group glowroot: no matching entries in group file.`
Sorry for not spotting this previously...

Fix Docker image unable to find group glowroot

---

central/Dockerfile

Addresses #934 
Relocate WORKDIR directive to be before the invocation of sed.

Fix #934 by relocating the WORKDIR directive

---

central/Dockerfile

My sysadmin kindly launched the Glowroot POD in debug mode.
The following was observed:
```
drwxr-xr-x. 1 glowroot root 32 May 27 08:41 /usr/share/glowroot-central
```
This finally shows, conclusively, that /usr/share/glowroot-central can be written to by user "glowroot" but not by any other user which happens to be a member of the "root" group.
OpenShift will ignore USER directives, and run the POD as a numbered userid which cannot possibly exist on the underlying physical host but which is guarranteed to be a member of the "root" group.
This PR ascribes g+w permission to the /usr/share/glowroot-central directory before sed attempts to open its temporary file in that location.

grant g+w to /usr/share/glowroot-central before sed invocation

---

agent/core/src/main/java/org/glowroot/agent/util/LazyPlatformMBeanServer.java

This simple PR enable run of glowroot agent on wildfly bootable jars (https://docs.wildfly.org/bootablejar/  -> https://mvnrepository.com/artifact/org.wildfly.core/wildfly-jar-boot).
Tested with:
org.wildfly.plugins:wildfly-jar-maven-plugin:8.0.1.Final
feature pack location: wildfly@maven(org.jboss.universe:community-universe)#26.1.2.Final
through jib image distroless/java17-debian11:latest
Thanks four your great work on glowroot!

Add in waitForContainerToCreatePlatform... wildfly bootable jar main class

---

agent/core/src/main/java/org/glowroot/agent/weaving/WeavingClassFileTransformer.java

Hi @trask 
with the new version of jdk, classes `sun/reflect/Generated` has been moved to `jdk/internal/reflect/Generated`.
This very simple PR aims at not weaving these classes.

Fix: do not weave jdk/internal/reflect/Generated*

---

ui/src/main/java/org/glowroot/ui/TransactionCommonService.java

Hello, 
On a fresh install of latest 0.14.5-beta release, I faced the following exception while clicking on "percentile" radio button : 
```
2025-08-08 12:27:29.786 ERROR o.g.a.e.s.o.g.ui.CommonHandler - java.lang.UnsupportedOperationException
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
at org.glowroot.agent.embedded.shaded.org.glowroot.ui.TransactionJsonService.getPercentiles(TransactionJsonService.java:156)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at …
```

Fix again #1072 UnsupportedOperationException in embedded collector
